### PR TITLE
[WIP] Recommend winget installation

### PR DESCRIPTION
**Pull request by jssblck**
# Overview

Recommend winget installation over PowerShell script or scoop.

TODO: Automate winget pushes via GitHub Action.

## Acceptance criteria

We agree that we want to recommend this over other options.

Feedback from the team has been that the PowerShell script doesn't always work as users expect, so recommending installation through Microsoft's official package manager seems ideal to me.

## Testing plan

On my Windows machine I used `winget` to install FOSSA and it worked flawlessly.
Also `winget` had been already installed, so this was a very native feeling experience.

## Risks

It's theoretically possible that `winget` becomes harder to work with in the future, making us not want to recommend it, although I think this is low risk. It's in Microsoft's best interest to make `winget` easy for developers to integrate with.

## References

Thanks to @superusercode for getting this started! Ref: https://github.com/fossas/fossa-cli/pull/1200

## Checklist

- [x] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [x] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [x] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [x] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

### CODE REVIEW

**Review by csasarak — APPROVED** [review]
I agree in general with recommending `winget` over powershell since it's a smoother experience and I assume less error-prone than powershell. 

I think we should want to wait on recommending it until we get the winget piece automated if it's not much more work. I'd have more confidence that we'll collectively keep it up to date that way unless the manual process is very simple. In that case I think it might be worth adding a checkbox to our PR template directing us to do the winget step if we're making a release. I couldn't find a very good way to do that a release notes template though that'd be ideal. What are your thoughts on this?

**Comment by jssblck** [comment]
> I agree in general with recommending `winget` over powershell since it's a smoother experience and I assume less error-prone than powershell.
> 
> I think we should wait on recommending it until we get the winget piece automated if it's not much more work.

That's a good idea. I'll dismiss your approval, mark this as draft, & get the automation added to this PR before we merge it.

**Comment by spatten** [comment]
I wrote up a ticket to automate winget releases in hopes that this helps get this work scheduled

https://fossa.atlassian.net/browse/ANE-1085

**Comment by jssblck** [comment]
Closing this to reduce open PRs, we can reopen as we decide to invest in this more.

**Pull request closed without merging**
