### PR TITLE
Fix ConcurrentModificationException that can happen when resolving Gradle dependencies. 

### PR DESCRIPTION
**Pull request by designedbyz**
# Overview

This PR improves the fossa-cli gradle init script plugin by using [`DomainObjectCollection.all()`](https://docs.gradle.org/current/javadoc/org/gradle/api/DomainObjectCollection.html#all-groovy.lang.Closure-) to process the dependencies instead of the Groovy collection function `each`. This reduces the risk that another plugin or build author's modifications to the configurations will result in the `jsonDeps` task encountering a `ConcurrentModificationException` while running. Extensive comments are added to the code. 

## Acceptance criteria

This PR should make it easier for customers to use fossa-cli with gradle projects, as it avoids a `ConcurrentModificationException` that can occur when accessing and traversing Gradle Configurations for complex projects because of modifications to the `Configurations` collection by other plugins. 

## Testing plan

I manually tested this change extensively against a project that is currently evaluating FOSSA as an SCA tool. Unfortunately, I am not sure what plugin conflicts with the init script, but my best guess is that fossa was conflicting with another Gradle plugin that my team is currently using manage dependency licenses, CashApp's [Licensee](https://github.com/cashapp/licensee). I _do_ know that the exception did not result from our own code, as I was still able to reproduce it if I commented out our calls to `project.configurations`

I've not added tests to the init script, as far easier to test [Binary Plugins](https://docs.gradle.org/current/userguide/plugins.html#sec:binary_plugins), and the init script is currently a script plugin that does extensive method declaration inside of a task, making unit testing the functionality incredibly difficult.  

## Risks

This should be pretty low risk; the only risk that I can think of is that someone is relying on the previous incorrect behavior :shudder:

## References

n/a at this time. 

## Checklist

- [x] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] ~~If this PR introduced a user-visible change, I added documentation into `docs/`.~~ n/a
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] ~~If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).~~ n/a

### CODE REVIEW

**Comment by designedbyz** [comment]
Working on figuring out the CLA stuff, will update when we get that figured out

**Comment by spatten** [comment]
Hi Andy,

Thanks for your PR! This looks like a good change to me, and we will very happily accept this once the CLA is signed.

Our CI will unfortunately not pass when running on your fork, so I will have to make a new PR, cherry-pick your commits in and approve that once the tests pass.

Thanks again for this. It is much appreciated.

Scott

**Comment by spatten** [comment]
> With regards to CI not running on my fork, is that just because it will only run on the original repo, or is there some setup I should do to my fork to make it work?

Unfortunately there's nothing that you can do here. We download some binaries in our CI build process, and some of those are not publicly available. Because of this, CI will only succeed when it has access to the secrets that are available in the fossas organization. 

Thanks,
Scott

**Comment by designedbyz** [comment]
> Unfortunately there's nothing that you can do here. We download some binaries in our CI build process, and some of those are not publicly available. Because of this, CI will only succeed when it has access to the secrets that are available in the fossas organization.

HI Scott, got it, I suspected it might be something like that. I just got approval to sign the CLA and have done so and added the work email that was on my commits to my Github profile, so I think we should be good to go!

**Comment by csasarak** [comment]
Hi @designedbyz, I made a new PR that includes your commits. Could you go over to #1171 and give it a quick look over and comment saying if it reflects everything you want included? Thanks!

**Comment by csasarak** [comment]
Closed in favor of #1171

**Pull request closed without merging**
