### PR TITLE
Container Scanning: dpkg status parser

### PR DESCRIPTION
**Pull request by jssblck**
# Overview

Provides a parser for parsing `/var/lib/dpkg/{status|status.d}`.

## Acceptance criteria

We can parse the file successfully.

## Testing plan

I relied on automated testing.

## References

[ANE-272](https://fossa.atlassian.net/browse/ANE-272)

## Checklist

- [x] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [ ] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

### CODE REVIEW

**Comment by jssblck** [comment]
@meghfossa this PR has a scary line count but 90% of it is testing data so can largely be ignored other than sanity checking 😅 sorry!

**Review by meghfossa — APPROVED** [review]
LGTM structurally, although a unit test failure will need fixing before merging. 

[no action] prefer we add this as a typical strategy (discoveryFunc/analysisFunc), similar to alpine, but that's ok; I/we can address all of this in a later milestone.

**Comment by jssblck** [comment]
Hmmmmm 🤔 
```
Running 1 test suites...
Test suite unit-tests: RUNNING...

Container.Dpkg
  Container Dpkg Parser
    parses a single simple entry [✔]
    parses a single realistic entry [✔]
    parses var/lib/dpkg/status [✔]
```

**Comment by jssblck** [comment]
Talked with @meghfossa offline: we're going to leave this PR as is and merge `dpkg` into the other container strategies in a separate PR to keep things simple.

**Pull request merged**
