### PR TITLE
Allow missing external sources field in podfile

### PR DESCRIPTION
**Pull request by zlav**
# Overview

Rename branch so that it can pass the link check parser due to the `]` in the branch name

Per [ANE-769](https://fossa.atlassian.net/browse/ANE-769), `fossa analyze` fails when scanning a Podfile.lock that does not contain an `EXTERNAL SOURCES` element. This PR makes `EXTERNAL SOURCES` an optional field. 

## Acceptance criteria

When scanning a Podfile.lock with no `EXTERNAL SOURCES` specified, `fossa analyze` should still succeed.

## Testing plan

I think @zlav has tested this for me and fixed a couple of things I missed.

## Risks

We're unsure whether there's a spec that states that this field can be optional, or why it wasn't made optional in this code in the first place.

## Metrics

n/a

## References

https://fossa.atlassian.net/browse/ANE-769
https://fossa.zendesk.com/agent/tickets/5565
https://fossa.zendesk.com/agent/tickets/6926
https://fossa.zendesk.com/agent/tickets/5751
https://fossa.zendesk.com/agent/tickets/6588

## Checklist

- [x] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [x] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).
- [ ] If I made changes to a subcommand's options, I updated `docs/references/subcommands/<subcommand>.md`.

[ANE-769]: https://fossa.atlassian.net/browse/ANE-769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by spatten — APPROVED** [review]
This change seems to have broken an integration test. The change makes sense to me, but we'll obviously have to fix the integration spec before merging

**Comment by ryanlink** [comment]
@zlav did you clone these changes into another PR / should I delete this one? or is it stuck in limbo?

**Comment by ryanlink** [comment]
Resurrecting this for ANE-769, what do we need to do to get it across the finish line?

**Comment by zlav** [comment]
@ryanlink thanks for the nudge. I modified the integration tests. This PR should auto-merge after the tests pass.

Integration-tests - This change turned one of our integration tests from detecting a partial graph to a complete graph due to the bug that is fixed in this PR. This is why the original fix was "failing" the test.

**Pull request merged**
