### PR TITLE
Use ISO timestamp for revision fallback

### PR DESCRIPTION
**Pull request by jssblck**
# Overview

We generate the revision for a project automatically, eventually falling back to the current timestamp.
Currently that timestamp is just a unix string. @rolodato suggested that this should be an ISO timestamp instead to make it more clear to users.

I thought this was super simple and a good idea so I just threw it in, but if anyone has a major issue with it happy to just close the PR.

This change isn't tested because I think we don't really have tests for this and adding it into tests would be more time investment than I think this change warrants. If you disagree though, let me know!

## Acceptance criteria

The final fallback for `--revision` is an ISO8601 timestamp instead of a unix epoch timestamp.

## Testing plan

I created a project with no `.git`:
```shell
; pwd
/Users/jessica/projects/scratch/tiny
; ls -al
total 24
drwxr-xr-x   7 jessica  staff   224 Nov  4 16:56 .
drwxr-xr-x  48 jessica  staff  1536 Oct 31 15:47 ..
-rw-r--r--   1 jessica  staff     8 Mar 16  2022 .gitignore
-rw-r--r--   1 jessica  staff   378 Mar 16  2022 Cargo.lock
-rw-r--r--   1 jessica  staff   195 Mar 16  2022 Cargo.toml
drwxr-xr-x   3 jessica  staff    96 Mar 16  2022 src
drwxr-xr-x@  5 jessica  staff   160 Aug 22 13:29 target
```

I then ran the scan:
```shell
; cabal run fossa -- analyze ~/projects/scratch/tiny
# ...
[ INFO] ------------
[ INFO]
[ INFO] Using project name: `tiny`
[ INFO] Using revision: `2022-11-04T23:57:26.932386Z`
[ INFO] Using branch: `No branch (detached HEAD)`
# ...
```

And checked the UI:
Screenshot 2022-11-04 at 5 02 58 PM

## Risks

Does not seem risky.

## Checklist

- [x] I added tests for this PR's change (or explained in the PR description why tests don't make sense).
- [ ] If this PR introduced a user-visible change, I added documentation into `docs/`.
- [x] If this change is externally visible, I updated `Changelog.md`. If this PR did not mark a release, I added my changes into an `# Unreleased` section at the top.
- [ ] If I made changes to `.fossa.yml` or `fossa-deps.{json.yml}`, I updated `docs/references/files/*.schema.json`. You may also need to update these if you have added/removed new dependency type (e.g. `pip`) or analysis target type (e.g. `poetry`).

### CODE REVIEW

**Review by zlav — APPROVED** [review]
Agreed that this is much clearer! Nice quick fix

**Comment by rolodato** [comment]
Thanks for this ✨ 

One nitpick - removing the milliseconds might look a lot cleaner, but either way this is a lot better than the current behavior.

**Comment by jssblck** [comment]
@rolodato Milliseconds removed, now it looks like this:

```
[ INFO] Using project name: `tiny`
[ INFO] Using revision: `2022-11-05T00:36:46`
```

Screenshot 2022-11-04 at 5 37 43 PM

Agreed, this looks even nicer! Thanks!

**Review by rolodato — APPROVED** [review]
The screenshot in this message caught me off guard as it doesn't have the UTC `Z` indicator: https://github.com/fossas/fossa-cli/pull/1091#issuecomment-1304358352

But I can see that there was a change added afterwards to make this compliant with the spec. Ship it! ✨

**Pull request merged**
